name: JMeter CI

on:
  push:
    branches: [ main, master, ci-implementation ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Fix code style
      run: ./gradlew autostyleApply
      continue-on-error: true
    
    - name: Build with Gradle
      run: ./gradlew build
      continue-on-error: true
    
    - name: Run tests
      run: ./gradlew test
      continue-on-error: true
